version: '3'
services:
  backend:
    build: .
    container_name: backend_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DB_NAME=database
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
    command: python manage.py runserver 0.0.0.0:8000

  database:
    image: postgres:16.4
    container_name: database_container
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
