version: '3'
services:
  backend:
    build: .
    container_name: todolist_backend_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000

  database:
    image: postgres:16.4
    container_name: todolist_database_container
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
