services:
  backend:
    build: .
    container_name: todolist_backend_container
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - database

  database:  # Este nombre debe coincidir con DB_HOST en .env
    image: postgres:16.4
    container_name: todolist_database_container
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: